defaults:
  - paths: default
  - inference: cpu
  - model: qwen3-8b-instruct
  - dataset: coding
  - wandb: online
  - _self_

run_name: default
prompt_stats_file: prompt_rollout_stats.pt
pooled_metrics_file: pooled_metrics.json
keep_fraction: 0.7
use_reward_filter: false

hydra:
  job:
    chdir: false
  run:
    dir: ${paths.outputs_root}/hydra_logs/${hydra.job.config_name}/single/${now:%Y-%m-%d}_${now:%H-%M-%S}
  sweep:
    dir: ${paths.outputs_root}/hydra_logs/${hydra.job.config_name}/multirun/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.num}
