defaults:
  - paths: default
  - inference: a100
  - launcher: process
  - model: qwen3-8b-instruct
  - dataset: coding
  - reward: skywork
  - _self_

run_name: default
resume: true
sweep_name: default

hydra:
  job:
    chdir: false
    config:
      override_dirname:
        exclude_keys:
          - experiment
  run:
    dir: ${paths.outputs_root}/hydra_logs/${hydra.job.config_name}/single/${now:%Y-%m-%d}_${now:%H-%M-%S}
  sweep:
    dir: ${paths.outputs_root}/hydra_logs/${hydra.job.config_name}/multirun/${sweep_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.num}_${hydra.job.override_dirname}
