# @package _global_
run_name: topk-5000
sweep_name: ablation-topk-5000

generate_mem_gb: 400
generate_timeout_min: 720

wandb:
  run_name: ${run_name}

sampling:
  top_k: 5000
  logprobs: 5000

inference:
  max_logprobs: 5000
  prompt_batch_size: 1
  sample_batch_size: 50
  gpu_memory_utilization: 0.85

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      model: qwen3-8b-base,qwen3-8b-instruct,llama-3.1-8b-base,llama-3.1-8b-instruct,gemma-3-12b-base,gemma-3-12b-instruct
      dataset: coding,completion,math,stories
