# @package _global_
defaults:
  - override /inference: a100

sweep_name: gemma-3-12b-matrix

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      model: gemma-3-12b-base,gemma-3-12b-instruct
      dataset: coding,completion,math,stories
