# @package _global_
defaults:
  - override /inference: a100

sweep_name: qwen3-8b-matrix

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      model: qwen3-8b-base,qwen3-8b-instruct
      dataset: coding,completion,math,stories
